#!/bin/bash

if [ -f "/var/log/cga-update-manager/cga-updater.log" ]; then
	
		echo "CGA-update-manager existente"
    sudo mv /usr/share/pyshared/cga-update-manager/upgrade_system.py-backup /usr/share/pyshared/cga-update-manager/upgrade_system.py
    notify-send "Auto actualizaciones activado"
    sudo apt-update
	else
		sudo mkdir -p /var/log/cga-update-manager/
		sudo touch /var/log/cga-update-manager/cga-updater.log
		sudo chmod 666 /var/log/cga-update-manager/cga-updater.log
		echo "CGA-update-manager reparado"
    sudo mv /usr/share/pyshared/cga-update-manager/upgrade_system.py-backup /usr/share/pyshared/cga-update-manager/upgrade_system.py
    notify-send "Auto actualizaciones activado"
    sudo apt update
fi


