#!/bin/bash
#clear

## variables
distribucion=$(lsb_release -cs)

#wget --no-check-certificate --content-disposition https://github.com/aosucas499/guadalinex/raw/main/apps-guadalinex-20

### Funciones del script
##		
		function installUbunturepo { 
		sudo echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main universe multiverse restricted" > focal.list
		sudo mv focal.list /etc/apt/sources.list.d/
		sudo apt update
		sudo apt install git gdebi -y
		}

		function unInstallUbunturepo {
 		sudo rm /etc/apt/sources.list.d/focal.list
		sudo apt update
		}
		
		function swapKernel { 
		sudo echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal-updates main universe multiverse restricted" > focal.list
		sudo mv focal.list /etc/apt/sources.list.d/
		sudo apt update
		clear
		sudo apt search linux-image*
		
		kernelnumber=$(zenity --entry \
                --title="Introduzca la versión del kernel a instalar" \
                --width=600 \
                --ok-label="Aceptar" \
                --cancel-label="Lo vamos a dejar" \
                --text="Use el formato siguiente o no funcionará: 5.10.0-1011-oem")
		ans=$?
		if [ $ans -eq 0 ]
			then
			echo "La versión introducida es: ${kernelnumber}"
			notify-send "La versión introducida es: ${kernelnumber}"
		else
    			echo "Otro día si eso..."
			sudo rm /etc/apt/sources.list.d/focal.list
			sudo apt update
    			exit
		fi
		sudo apt-get install -f -y
		sudo apt-get install linux-headers-$kernelnumber -y
		sudo apt-get install -f -y
		sudo apt-get install linux-image-$kernelnumber -y
		sudo apt-get install -f -y
		sudo apt-get install linux-modules-$kernelnumber -y
		sudo apt-get install -f -y
		sudo apt-get install linux-modules-extra-$kernelnumber -y
		sudo apt-get install -f -y
		sudo apt-get install linux-firmware -y
		sudo apt-get install -f -y
		sudo update-grub2
		sudo rm /etc/apt/sources.list.d/focal.list
		sudo apt update
		sudo apt-get autoremove -y
		}

		
		function installQshutdown {
		echo ""
		echo "Ejecute este aplicación cada vez que cree un usuario nuevo"
		echo ""
		
		#read shutdowntime
		shutdowntime=$(zenity --entry \
                --title="Introduzca la hora para el apagado automático diario del equipo" \
                --width=500 \
                --ok-label="Aceptar" \
                --cancel-label="Lo vamos a dejar" \
                --text="Use el formato siguiente o no funcionará: 14:00")
		ans=$?
		if [ $ans -eq 0 ]
			then
			echo "La hora introducida es: ${shutdowntime}"
		else
    			echo "Otro día si eso..."
    			exit
		fi
		sudo echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main universe multiverse restricted" > focal.list
              	sudo mv focal.list /etc/apt/sources.list.d/
             	sudo apt update
		sudo apt instausuarioll qshutdown
		sudo rm /etc/apt/sources.list.d/focal.list
		sudo apt update
		mkdir ~/.qshutdown
		cp ./qshutdown/qshutdown.conf ~/.qshutdown/
		sed -i -e "s/14:01/$shutdowntime/g" ~/.qshutdown/qshutdown.conf
		
		#Si hay un usuario = usuario lo establece también
		if [ -d "/home/usuario" ]; then
			sudo mkdir /home/usuario/.qshutdown
			sudo cp ./qshutdown/qshutdown.conf /home/usuario/.qshutdown/qshutdown.conf
			sudo sed -i -e "s/14:01/$shutdowntime/g" /home/usuario/.qshutdown/qshutdown.conf
			sudo cp /usr/share/applications/qshutdown.desktop /etc/xdg/autostart/
		else	
		sudo cp /usr/share/applications/qshutdown.desktop /etc/xdg/autostart/
		fi
		
		userQshutdown=$(zenity --entry \
                --title="Instalación de apagado automático para otro usuario" \
                --width=500 \
                --ok-label="Aceptar" \
                --cancel-label="Lo vamos a dejar" \
                --text="Escriba el nombre de usuario")
		ans=$?
		if [ $ans -eq 0 ]
			then
			echo "Instalado el apagado para el usuario: ${userQshutdown}"
		else
    			echo "Otro día si eso..."
    			exit
		fi
		
		#Instalamos para el usuario anterior si es introducido
		if [ -d "/home/$userQshutdown" ]; then
			sudo mkdir /home/$userQshutdown/.qshutdown
			sudo cp ./qshutdown/qshutdown.conf /home/$userQshutdown/.qshutdown/qshutdown.conf
			sudo sed -i -e "s/14:01/$shutdowntime/g" /home/$userQshutdown/.qshutdown/qshutdown.conf
			sudo cp /usr/share/applications/qshutdown.desktop /etc/xdg/autostart/
		else	
		sudo cp /usr/share/applications/qshutdown.desktop /etc/xdg/autostart/
		fi
		
		
		}
		
		function installDocker {
		# Por repositorio
			#sudo echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main universe multiverse restricted" > focal.list
              		#sudo mv focal.list /etc/apt/sources.list.d/
             		#sudo apt update
			#clear
			#sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
			#sudo apt install -f
			#sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
			#sudo echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $distribucion stable" > docker.list
			#sudo mv docker.list /etc/apt/sources.list.d/
			#sudo apt-key fingerprint 0EBFCD88
			#sudo apt update
			#clear
			#sudo apt install docker-ce docker-ce-cli containerd.io -y
			#sudo usermod -aG docker $USER
			#sudo usermod -aG docker usuario
			#sudo rm /etc/apt/sources.list.d/focal.list
			#sudo rm /etc/apt/sources.list.d/docker.list
			#sudo apt update
			#sleep 30
			
		# Por paquetes
		echo ""
		echo -e "${AZUL}Instalando Docker...${NORMAL}"
		echo ""
		echo -e "${AZUL}Instaling Docker...${NORMAL}"
		echo ""
		sudo apt update
		sudo apt install -f
		sudo apt-get install screen gir1.2-appindicator3-0.1 apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
		wget https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/containerd.io_1.5.11-1_amd64.deb
		wget https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce-cli_20.10.17~3-0~ubuntu-focal_amd64.deb
		wget https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce_20.10.17~3-0~ubuntu-focal_amd64.deb
		sudo dpkg -i *.deb
		sudo apt install -f
		sudo rm *.deb
		sleep 30
		
		}
		
		# Función para instalar las flatpak y sus dependencias 

		function flatpakInstall {

			if dpkg-query --list | grep gnome-software-plugin-flatpak; then
        			echo "Flatpak instalado"
			else
        			echo "Flatpak no instalado"
				notify-send "Espere...Instalando Flatpak"
				sudo rm /etc/apt/sources.list.d/focal.list
				sudo echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main universe multiverse restricted" > focal.list
				sudo mv focal.list /etc/apt/sources.list.d/focal.list
				sudo apt-get update -y 
				sudo apt-get install -y libflatpak0
				sudo apt-get install -y flatpak
				sudo wget https://github.com/aosucas499/guadalinex/raw/main/src/gnome-software-plugin-flatpak_3.36.1-0ubuntu0.20.04.0eos_amd64.deb
				sudo dpkg -i gnome-software-plugin-flatpak_3.36.1-0ubuntu0.20.04.0eos_amd64.deb
				sudo rm gnome-software-plugin-flatpak_3.36.1-0ubuntu0.20.04.0eos_amd64.deb
				sudo rm /etc/apt/sources.list.d/focal.list
				sudo apt-get update -y 
				echo "Flatpak instalado"
				notify-send "Flatpak instalado"
				fi
			# Preguntamos al usuario si quiere añadir los repositorios flatpak a gnome-software
			zenity --question \
       			--title="¿Añadir repositorio flatpak a Centro de Software EducaAndOS?" \
       			--width=600 \
       			--text="¿Añadir repo flatpak a Centro Software EOS? En caso afirmativo, las apps le apareceran para instalar en el centro de software de EducaAndOS"
			ans=$?		
				if [ $ans -eq 0 ]
				then
    					echo "Repo flatpak añadido a Centro de software EOS"
					notify-send "Repo flatpak añadido a Centro de software EOS"
					notify-send "Reinicie y le aparecerán en el Centro de software EOS"
					sudo apt-get update -y
					sudo apt-get install curl -y
					curl -o flathub.flatpakrepo https://flathub.org/repo/flathub.flatpakrepo 
					sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
				else
    					echo "Repo flatpak NO añadido a Centro de software EOS"
					notify-send "Repo flatpak NO añadido a Centro de software EOS"
					notify-send "Podrá instalar apps flatpak usando la terminal"
				fi
				
		}

		function installNtpfix {
		sudo cp ./ntp/fix-ntp /usr/bin
		sudo chmod +x /usr/bin/fix-ntp
		sudo chown root:root ./ntp/zz-fix-ntp
		sudo chmod 0440 ./ntp/zz-fix-ntp
		sudo cp ./ntp/zz-fix-ntp /etc/sudoers.d/ 
		sudo cp ./ntp/fix-ntp.desktop /etc/xdg/autostart/
		} 
		
		function installOpenboard {
		sudo apt update        	
		sudo apt install openboard -y
		}
		
		function installChrome {
		wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
		sudo echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > chrome.list
		sudo mv chrome.list /etc/apt/sources.list.d/
		sudo apt update
		sudo apt install google-chrome-stable
		sudo rm /etc/apt/sources.list.d/chrome.list
		sudo apt update
		}

		function installBlinklearning {
		wget https://blinklearning1.blob.core.windows.net/installers/blinkoffline/blinkoffline.sh 
		chmod +x blinkoffline.sh
		./blinkoffline.sh
		#rm ~/Escritorio/blink*
		# Fix folder for slim
		#rm ~/Desktop/blink*
		if [ -d "/home/usuario" ]; then
			echo ""
			echo "Introduce la contraseña del usuario = usuario"
			echo ""
			echo "para instalarlo en la cuenta usuario"
			echo ""
           		su usuario -c ./blinkoffline.sh 				
			#sudo rm /home/usuario/Escritorio/blin*
			# Fix folder for slim
			#sudo rm /home/usuario/Desktop/blin*
			sudo rm blinkoffline.sh
			else
		rm blinkoffline.sh
		fi
		}
		
		function installsm {
		wget https://downloads.smaprendizaje.com/apps/smaprendizaje/smaprendizaje_1_11_5_64.run
		chmod +x smaprendizaje_1_11_5_64.run
		./smaprendizaje_1_11_5_64.run
		sed -i -e '$a Categories=Education' /home/$USER/Desktop/SM\ Aprendizaje.desktop
		cp /home/$USER/Desktop/SM\ Aprendizaje.desktop /home/$USER/.local/share/applications/
		# Fix para reparar el fallo de la aplicación. Olvidaron en el acceso directo renombrar al nuevo nombre de la app.
		sudo cp /home/$USER/aprendizaje/SMAprendizaje-linux-x64/aprendizaje /home/$USER/aprendizaje/SMAprendizaje-linux-x64/SMAprendizaje
		sudo chown $USER:$USER /home/$USER/aprendizaje/SMAprendizaje-linux-x64/SMAprendizaje
		if [ -d "/home/usuario" ]; then
			echo ""
			echo "Introduce la contraseña del usuario = usuario"
			echo ""
			echo "para instalarlo en la cuenta usuario"
			echo ""
           		su usuario -c ./smaprendizaje_1_11_5_64.run 				
			sudo sed -i -e '$a Categories=Education' /home/usuario/Desktop/SM\ Aprendizaje.desktop
			sudo chown usuario:usuario /home/usuario/Desktop/SM\ Aprendizaje.desktop
			sudo cp /home/usuario/Desktop/SM\ Aprendizaje.desktop /home/usuario/.local/share/applications/
			# Fix para reparar el fallo de la aplicación. Olvidaron en el acceso directo renombrar al nuevo nombre de la app.
			sudo cp /home/usuario/aprendizaje/SMAprendizaje-linux-x64/aprendizaje /home/usuario/aprendizaje/SMAprendizaje-linux-x64/SMAprendizaje
			sudo chown usuario:usuario /home/usuario/aprendizaje/SMAprendizaje-linux-x64/SMAprendizaje
			sudo rm smaprendizaje_1_11_5_64.run
			else
		rm smaprendizaje_1_11_5_64.run
		fi
		}
		
		function installsantillana {
		wget https://prod.santillana.es/downloads/av/linux.tar.gz
		tar -xzvf linux.tar.gz
		chmod +x aulavirtual-3.3.4-linux-x64-installer.run
		./aulavirtual-3.3.4-linux-x64-installer.run
		sed -i -e '$a Categories=Education' /home/$USER/Desktop/Aula\ Virtual.desktop
		cp /home/$USER/Desktop/Aula\ Virtual.desktop /home/$USER/.local/share/applications/
		if [ -d "/home/usuario" ]; then
			echo ""
			echo "Introduce la contraseña del usuario = usuario"
			echo ""
			echo "para instalarlo en la cuenta usuario"
			echo ""
           		su usuario -c ./aulavirtual-3.3.4-linux-x64-installer.run				
			sudo chown $USER:$USER /home/usuario/Desktop/Aula\ Virtual.desktop
			sudo sed -i -e '$a Categories=Education' /home/usuario/Desktop/Aula\ Virtual.desktop
			sudo chown usuario:usuario /home/usuario/Desktop/Aula\ Virtual.desktop
			sudo cp /home/usuario/Desktop/Aula\ Virtual.desktop /home/usuario/.local/share/applications/
			sudo rm aulavirtual-3.3.4-linux-x64-installer.run
			sudo rm linux.tar.gz
			else
		rm aulavirtual-3.3.4-linux-x64-installer.run
		rm linux.tar.gz
		fi
		}
		
		function installActivdre {
		git clone https://github.com/aosucas499/activdre.git
		cd activdre
		chmod +x educaandos.sh
		./educaandos.sh
		cd ..
		}
		
		function installSmartdre {
		git clone https://github.com/aosucas499/smartdre.git
		cd smartdre
		chmod +x install-eos
		./install-eos
		cd ..
		}
		
		function installSmartboard480 {
		# Paquete oficial smartboard de eos
		# Comprobamos que está instalado desde gnome-software
		# en caso contrario lanzamos la tienda para que instale
		# y pedimos al usuario que lanze otra vez la instalación.
		sudo apt update -y
		if dpkg-query --list | grep smartboard-meta; then
        		echo "Smartboard eos instalado"
			# añadimos drivers para smartboard 480
			sudo apt-get install git -y
			sudo apt-get install dkms -y
			git clone https://github.com/aosucas499/nwfermi
			cd nwfermi
			chmod +x nwfermi-lliurex.sh
			sudo ./nwfermi-lliurex.sh
			cd ..
			sudo rm -r nwfermi
			echo "Drivers modelo 480 instalados"
			notify-send "Drivers modelo 480 instalados"
			notify-send "Reinicie para que funcione la pizarra"
		else
			echo "Smartboard EOS no instalado"
			notify-send "Smartboard EOS no instalado"
			zenity --error \
       			--title="Smartboard EOS no instalado" \
      			--width=500 \
      			--text="Instale la aplicación <b>Pizarra Smartboard</b> desde el centro de software EducaAndOS y vuelva a ejecutar esta instalación"
			gnome-software --details-pkg=smartboard-meta
		fi
		}
		
		function installStarboardre {
		cd /home/$USER
		git clone https://github.com/aosucas499/starboardre.git
		cd starboardre
		chmod +x install-eos
		./install-eos
		cd $OLDPWD
		}
		
		function installSigala {
		cd /home/$USER/
		git clone https://github.com/aosucas499/hgr-dre.git 
		cd hgr-dre
		chmod +x install-eos
		./install-eos
		}
		
		function installBells {
		cd /home/$USER/
		git clone https://github.com/aosucas499/bellscheduler-dre.git 
		cd bellscheduler-dre
		chmod +x install-eos
		./install-eos
		}
		
		function usuario {
		echo ""
		echo "Esta opción no debe combinarse con otras hasta que"
		echo "entre en la sesión del nuevo usuario gráficamente"
		echo ""
		echo "Otras aplicaciones necesitan instalar en carpetas"
		echo "que aún no han sido creadas hasta que entre en la sesión gráfica"
		echo ""
		echo "Despúes de crear el usuario, ejecute esta app otra vez"
		echo "e instale lo que necesite que pueda involucrar a ambos usuarios"
		echo ""
		echo ""
		echo "Ingrese el nombre del nuevo usuario sin permisos root"
		echo ""
		read usuario
		if [ "$usuario" == "" ] ; then
  			echo -e "\n"
  			echo "El nombre no puede estar vacío, ejecute el script otra vez."
  			echo -e "\n"
  			exit 1
  			fi
  		if [ "$?" != 0 ] ; then
   			echo -e "\n"
  			echo "Ha ocurrido un error, asegurese de que los datos ingresados son correctos."
  			exit 1
			fi
		echo -e "\n"
		sudo useradd -m -d /home/$usuario -G adm,cdrom,dip,plugdev,lpadmin,sambashare,dialout $usuario -s /bin/bash
		echo "Ingrese una contraseña para el usuario, $usuario"
		sudo passwd $usuario
		echo -e "\n"echo "El usuario fue creado satisfactoriamente"
		}

		function installkazam {
		sudo echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main universe multiverse restricted" > focal.list
              	sudo mv focal.list /etc/apt/sources.list.d/
             	sudo apt update
		sudo apt install kazam -y
		sudo sed -i 's/time.clock/time.perf_counter/g' /usr/lib/python3/dist-packages/kazam/pulseaudio/pulseaudio.py
		sudo rm /etc/apt/sources.list.d/focal.list
		sudo apt update
		}	
		
		function installgparted {
		sudo echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main universe multiverse restricted" > focal.list
              	sudo mv focal.list /etc/apt/sources.list.d/
             	sudo apt update
		sudo apt install gparted -y
		sudo rm /etc/apt/sources.list.d/focal.list
		sudo apt update
		sudo sed -i -e 's/Terminal=false/Terminal=true/g' /usr/share/applications/gparted.desktop
		sudo sed -i -e 's/Exec=/#Exec=/g' /usr/share/applications/gparted.desktop
		sudo sed -i -e '$a Exec=sudo /usr/sbin/gparted' /usr/share/applications/gparted.desktop
		}	
		
		function restore_usuario {
		echo ""
		echo "Esta opción no debe combinarse con otras hasta que"
		echo "entre en la sesión del usuario restaurado gráficamente"
		echo ""
		echo "Otras aplicaciones necesitan instalar en carpetas"
		echo "que aún no han sido creadas hasta que entre en la sesión gráfica"
		echo ""
		echo "Despúes de restablecer el usuario, ejecute esta app otra vez"
		echo "e instale los nuevos programas que necesite que pueda involucrar a ambos usuarios"
		echo ""
		echo ""
		echo "Ingrese el nombre del usuario que quiere restablecer a valores de fábrica"
		echo ""
		read usuario
		if [ "$usuario" == "" ] ; then
  			echo -e "\n"
  			echo "El nombre no puede estar vacío, ejecute el script otra vez."
  			echo -e "\n"
  			exit 1
  			fi
  		if [ "$?" != 0 ] ; then
   			echo -e "\n"
  			echo "Ha ocurrido un error, asegurese de que los datos ingresados son correctos."
  			exit 1
			fi
		echo -e "\n"
		sudo userdel -r $usuario
		sudo useradd -m -d /home/$usuario -G adm,cdrom,dip,plugdev,lpadmin,sambashare,dialout $usuario -s /bin/bash
		echo "Ingrese una contraseña para el usuario, $usuario"
		sudo passwd $usuario
		echo -e "\n"echo "El usuario fue creado satisfactoriamente"
		}
		
		function installMee {
		cd /home/$USER
		wget --header="Host: lms-api.macmillan.education" --header="User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36" --header="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" --header="Accept-Language: es-ES,es;q=0.9" --header="Referer: https://myclasses.macmillaneducationeverywhere.com/" "https://lms-api.macmillan.education/ACEApi/PdfExport/downloadapp?environmentId=linux64bit&appType=meeTeacherApps&userType=macmillanTeacherAdminLinux64" -c -O 'MacmillanEducationTeacher-Admin-Linux-x64.zip'
		unzip Mac*.zip
		rm Mac*.zip
		sudo dpkg -i Mac*.deb
		rm Mac*.deb
		sudo sed -i 's/Categories=GNOME;GTK;Utility;/Categories=Education;/g' /usr/share/applications/macmillaneducationteacher.desktop
		}
		
# Ejecuta la función correspondiente a cada una de las opciones del script
# ---

function ejecutarAccionOpcional {

    echo "Ejecutamos $1()"
    ($1)
}


# Invocamos ("callback") las funciones asociadas a las opciones 
# seleccionadas por el usuario


		function procesarAccionesOpcionales {

    		# Dividimos (el separador es "|" ) las opciones seleccionadas por el usuario
   
		IFS="|" read -a vals <<< $1

	    	# Solicitamos (una a una) que se procesen dichas opciones

    		for i in "${vals[@]}"
    		do
        	ejecutarAccionOpcional $i
    		done
		}

# ----------------------------------------------------------------------------
# Cuerpo del script
# ----------------------------------------------------------------------------

# Realizamos las opciones por defecto de nuestro script

# Permitimos seleccionar opciones personalizadas

# Mostramos las opciones personalizables

opc=$( \
    zenity \
        --list \
        --title="Elija las personalizaciones que desea aplicar" \
        --checklist \
        --column="Aplicar" \
        --column="funcionAEjecutar" \
        --column="Descripción" \
        --hide-column=2 \
        --width=625 \
        --height=800 \
    False usuario "Crear usuario sin derechos admin. No combine esta opción con otras." \
    False restore_usuario "Restablece un usuario a valores originales. No combine esta opción con otras." \
    False installQshutdown "Instalar Apagado automático a las XX:XX horas de L-V (app qshutdown)" \
    False installNtpfix "Instalar corrección de hora en equipos conectados por wifi" \
    False installOpenboard "Instalar aplicación de pizarra Openboard" \
    False installActivdre "Instalar drivers pizarras Promethean y aplicación ActivInspire" \
    False installSmartdre "Instalar drivers pizarras Smartboard-docker incluida SB480 (eos+)" \
    False installStarboardre "Instalar drivers pizarras Hitachi Starboard" \
    False installSigala "Instalar aplicación HGR-Sigala Servidor y cliente" \
    False installBells "Instalar Bell Scheduler - Programador alarmas con sonido" \
    False installChrome "Instalar navegador Chrome - siempre actualizado" \
    False installsm "Instalar aplicación Editorial SM - Aprendizaje" \
    False installsantillana "Instalar aplicación Santillana Aula Virtual" \
    False installBlinklearning "Instalar aplicación Blinklearning - Usado en libros de Oxford" \
    False installMee "Instalar aplicación MacMillan Education Everywhere" \
    False installkazam "Instalar grabador de escritorio Kazam" \
    False installgparted "Instalar Gparted, manejador de disco/particiones" \
    False flatpakInstall "Instalar Flatpak" \
    False installDocker "Instalar Docker" \
    False installUbunturepo "Instalar repositorios Ubuntu 20 Focal" \
    False unInstallUbunturepo "Desinstalar repositorios Ubuntu 20 Focal" \
    False swapKernel "Actualizar kernel del sistema" \
)

# Comprobamos que no se pulse el botón Cancelar

	if [[ "$?" != 0 ]]; then
    	echo "Sin problemas, ya personalizaremos otro día ;)"
    	exit 0
	fi

# Procesamos las opciones elegidas por el usuario
# ---

	procesarAccionesOpcionales $opc

#
