#! /bin/bash

clear
# Variables de color de script
#
ROJO="\033[1;31m"
NORMAL="\033[0m"
AZUL="\033[1;34m"

DISTRO=$(lsb_release -cs)

echo ""	
echo -e "${ROJO}Solicitando contraseña del usuario con derechos de administrador${NORMAL}"
echo ""
echo -e "${ROJO}Asking password of the user with administrations rights${NORMAL}"
echo ""
sudo echo ""

#Instalación paquetes/drivers nwfermi en el sistema host
#
if [[ $DISTRO = focal ]]
then
	echo ""
	echo -e "${AZUL}Tu sistema Linux está basado en Ubuntu focal${NORMAL}"
	echo ""
	echo -e "${AZUL}Your system is based on Ubuntu Focal${NORMAL}"
	echo ""
	sleep 4
	git clone https://github.com/aosucas499/nwfermi
	cd nwfermi
	chmod +x nwfermi-focal.sh
	sudo ./nwfermi-focal.sh
	sudo rm -r nwfermi
	
elif [[ $DISTRO = bionic ]]
then
	echo ""
	echo -e "${AZUL}Tu sistema Linux está basado en Ubuntu bionic${NORMAL}"
	echo ""
	echo -e "${AZUL}Your system is based on Ubuntu Bionic${NORMAL}"
	echo ""
	sleep 4
	git clone https://github.com/aosucas499/nwfermi
	cd nwfermi
	chmod +x nwfermi-bionic.sh
	sudo ./nwfermi-bionic.sh
	sudo rm -r nwfermi
	
elif [[ $DISTRO = ulyana ]]
then
	echo ""
	echo -e "${AZUL}Tu sistema Linux está basado en Ubuntu focal${NORMAL}"
	echo ""
	echo -e "${AZUL}Your system is based on Ubuntu Focal${NORMAL}"
	echo ""
	sleep 4
	git clone https://github.com/aosucas499/nwfermi
	cd nwfermi
	chmod +x nwfermi-focal.sh
	sudo ./nwfermi-focal.sh
	sudo rm -r nwfermi
	
elif [[ $DISTRO = ulyssa ]]
then
	echo ""
	echo -e "${AZUL}Tu sistema Linux está basado en Ubuntu focal${NORMAL}"
	echo ""
	echo -e "${AZUL}Your system is based on Ubuntu Focal${NORMAL}"
	echo ""
	sleep 4
	git clone https://github.com/aosucas499/nwfermi
	cd nwfermi
	chmod +x nwfermi-focal.sh
	sudo ./nwfermi-focal.sh
	sudo rm -r nwfermi

else
	echo ""
	echo -e "${ROJO}Esta instalación no es compatible con tu sistema${NORMAL}" 
	echo ""
	echo -e "${ROJO}This install process is not compatible with your system${NORMAL}"
	echo ""
	sleep 4
	exit
fi
echo ""
echo -e "${AZUL}continúa el script...${NORMAL}"
echo ""
echo -e "${AZUL}the script continues...${NORMAL}"
echo ""
