#!/bin/bash
#wget --no-check-certificate --content-disposition https://github.com/aosucas499/guadalinex/raw/main/ubuntudesktop
#wget --no-check-certificate --content-disposition https://bit.ly/3neWWiP
clear


#sudo echo "deb [arch=amd64] http://centros.edu.guadalinex.org/Edu/focal educaandos main" > /etc/apt/sources.list.d/guadalinex.list
#sudo echo "deb [arch=amd64] http://centros.edu.guadalinex.org/Edu/focalsc educaandos main" >> /etc/apt/sources.list.d/guadalinex.list
#sudo echo "deb [arch=amd64] http://centros.edu.guadalinex.org/Edu/focalscpdi educaandos main" >> /etc/apt/sources.list.d/guadalinex.list
#sudo echo "deb [arch=amd64] http://centros.edu.guadalinex.org/Edu/focalscmd educaandos main" >> /etc/apt/sources.list.d/guadalinex.list
#wget http://centros.edu.guadalinex.org/Edu/focal/pool/main/c/cga-sourceslist-config/cga-sourceslist-config_0.3-2_all.deb
#sudo dpkg -i cga-sourceslist-config_0.3-2_all.deb 

# Añade repositorios ubuntu y educaandos
	sudo apt-get install git -y
	sudo killall update-notifier
	sudo killall unattended-upgr
	sudo killall gnome-initial-setup
	sudo apt-get remove gnome-initial-setup -y
	wget --no-check-certificate --content-disposition https://github.com/aosucas499/sources/raw/main/educaandos.list
	#wget --no-check-certificate --content-disposition https://github.com/aosucas499/sources/raw/main/focal-modify-sources.list
	sudo rm /etc/apt/sources.list
	#sudo mv focal-modify-sources.list /etc/apt/sources.list
	sudo mv educaandos.list /etc/apt/sources.list.d/guadalinex.list

	wget http://centros.edu.guadalinex.org/Edu/focal/pool/main/e/educaandos-keyring/educaandos-keyring_0.3-4_amd64.deb
	sudo dpkg -i educaandos-keyring_0.3-4_amd64.deb
	sudo rm *.deb

# Actualiza ubuntu mini a educaandos

	sudo mkdir /usr/share/icons/EducaAndOS -p
	sudo mkdir /usr/share/icons/EducaAndOSIcons -p
	sudo apt update -y
	DEBIAN_FRONTEND=noninteractive sudo apt install educaandos-educacion-tic --no-install-recommends -y
	sudo rm /etc/apt/sources.list.d/guadalinex.list
	wget http://centros.edu.guadalinex.org/Edu/focal/pool/main/c/cga-sourceslist-config/cga-sourceslist-config_0.3-2_all.deb
	sudo dpkg -i cga-sourceslist-config_0.3-2_all.deb
	sudo apt update -y
	sudo apt upgrade -y
	sudo dpkg-reconfigure libdvd-pkg
	sudo apt-get clean
	sudo apt-get --purge -f -y autoremove
	sudo gnome-extensions disable ubuntu-dock@ubuntu.com

# Script con la opción de crear usuario con derechos sudo o no


#Menu opciones
	echo ""
	echo ""
	echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
	echo " 1. Salir"
	echo " 2. Actualizar a Educaandos con usuario administrador distinto de root."
	echo " 3. Actualizar a Educaandos sin usuario administrador, para usar en el centro." 
	echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
	echo ""
	echo ""
	while true; do
	read -p "Seleccione una opción, 1, 2 o 3: " op
	case $op in

[1]* ) exit;;
[2]* )
	#clear
	# Introducción al script crear usuario admin
	echo ""
	echo ""
	echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
	echo "Crearemos un usuario con derechos de administrador distinto de root. Por ejemplo, admin."
	echo ""
	echo "Este script tiene que ser ejecutado con derechos root: sudo ./ubuntudesktop"
	echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

	echo ""
	echo ""

	#Crear usuario administrador
	echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
	echo "Ingrese el nombre del nuevo usuario administrador, distinto de root."
	echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

	echo ""
	read usuario
	if [ "$usuario" == "" ] ; then
  	echo -e "\n"
  	echo "El nombre no puede estar vacío, ejecute el script otra vez."
  	echo -e "\n"
  	exit 1
	fi
	#sudo groupadd -r sambashare
	sudo groupadd -r admin
	sudo useradd -m -d /home/$usuario -g admin -G sudo,adm,cdrom,dip,plugdev,lpadmin,sambashare $usuario -s /bin/bash
	if [ "$?" != 0 ] ; then
   	echo -e "\n"
  	echo "Ha ocurrido un error, asegurese de que los datos ingresados son correctos."
  	exit 1
	fi
	echo -e "\n"
	echo "Ingrese una contraseña para el usuario con derechos de administrador, $usuario"
	sudo passwd $usuario
	echo -e "\n"
	echo "El usuario fue creado satisfacto clonarriamente"; break;;

[3]* ) break;;
esac
done


echo ""
echo "El sistema se ha actualizado a Educaandos, apague la máquina"
echo ""
echo "Puede usar el comando: sudo shutdown -P now"


