#!/bin/bash

#Variables

gitfolder=/home/$USER/guadalinex
gitguadalinex=https://github.com/aosucas499/guadalinex
branch=slim
source=/etc/apt/sources.list
source2=/etc/apt/sources.list.d/educaandossc.list
background=/usr/share/backgrounds/educaandos_slim_wallpaper.png
bgsize=$(du $background|cut -f 1)
sourceSize=$(du -b $source|cut -f 1)
source2Size=$(du -b $source2|cut -f 1)
isConnectionAvailable=$(echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1 && echo "True" || echo "False")
upgradeApp=/usr/share/pyshared/cga-update-manager/upgrade_system.py
upgradeSize=$(du -b $upgradeApp|cut -f 1)

# Comprobamos si hay internet
# ---

function isOnline {

if [[ $isConnectionAvailable == "False" ]]; then
	zenity --no-wrap \
        --warning \
        --title "Sin conexión a Internet" \
        --text "Es necesaria conexión a Internet para poder utilizar esta app."
        
    exit 1;
fi 

echo ""
echo "Hay conexión a Internet. Seguimos..."
echo ""
}

# Función que comprueba que el usuario que lanza la app tiene derechos admin.

function adminGroup {

        if getent group admin tde |grep $USER; then
                echo "El usuario pertenece al grupo admin y/o tde, continuamos..."
        else
               zenity --no-wrap \
       		--warning \
        	--title "No tiene derechos de administrador" \
        	--text "Contacte con su Coordinador/a TDE para instalar aplicaciones."
        
    		exit 1;
        fi
}

# Función que repara las actualizaciones de cga-update-manager
# por alguna razón en las versiones previas de la versión "plus"
# muestra un error

function fixCgaupdate {

	if [ -f "/var/log/cga-update-manager/cga-updater.log" ]; then
	
		echo "CGA-update-manager existente"
	else
		sudo mkdir -p /var/log/cga-update-manager/
		sudo touch /var/log/cga-update-manager/cga-updater.log
		sudo chmod 666 /var/log/cga-update-manager/cga-updater.log
		echo "CGA-update-manager reparado"
		notify-send "CGA-update-manager reparado"
	fi
}

# Función que repara el fondo de educaandos plus cuando es cambiado por cga para la versión oficial en alguna actualización.

function fixBackground {

		#echo "$bgsize"
	if [[ $bgsize = "456" ]]; then
		#echo "$bgsize"
		echo "Fondo de pantalla incorrecto, corrigiendo..."
		notify-send "Fondo de pantalla incorrecto, corrigiendo..."
		sudo wget https://github.com/aosucas499/guadalinex/raw/main/isobuilder/eggs/educaandos_slim_wallpaper-plus.png -O /tmp/educaandos_slim_wallpaper-plus.png
		sudo cp /tmp/educaandos_slim_wallpaper-plus.png /usr/share/backgrounds/educaandos_slim_wallpaper.png
	else
		#echo "$bgsize"
		echo "fondo de pantalla apropiado"
	fi
}	

function fixSource {

	
	if [[ $sourceSize = "77" ]]; then
		
		echo "Fichero sources.list apropiado"
	else
		sudo wget https://raw.githubusercontent.com/aosucas499/sources/main/eos-sources.list -O /tmp/sources.list
		sudo cp /tmp/sources.list $source
		sudo apt update -y
		echo "Fichero sources.list corregido"
		notify-send "Fichero sources.list corregido"
	fi
}

function fixSource2 {

	
	if [[ $source2Size = "329" ]]; then
		
		echo "Fichero sources2.list apropiado"
	else
		sudo wget https://raw.githubusercontent.com/aosucas499/sources/main/eos-educaandossc.list -O /tmp/educaandossc.list
		sudo cp /tmp/educaandossc.list $source2
		sudo apt update -y
		echo "Fichero sources.list2 corregido"
		notify-send "Fichero sources.list2 corregido"
	fi
}

function fixUpgrade {

	
	if [[ $upgradeSize = "19553" ]]; then
		
		echo "upgrade_system apropiado"
	else
		sudo wget https://raw.githubusercontent.com/aosucas499/guadalinex/slim/src/upgrade_system.py -O /tmp/upgrade_system.py
		sudo cp /tmp/upgrade_system.py $upgradeApp
		echo "Fichero de actualización automática corregido"
		echo "Ahora las actualizaciones automáticas preguntarán antes de instalarse"
		notify-send "Fichero de actualización automática corregido"
		notify-send "Ahora las actualizaciones automáticas preguntarán antes de instalarse"
	fi
}

function arduinoGroup {

	if groups $USER | grep -q "dialout"; then
		echo "El usuario pertenece al grupo dialout"
	else
		echo "El usuario no pertenece al grupo, corrigiendo..."
		notify-send "El usuario no pertenece al grupo, corrigiendo..."
		sudo usermod -a -G dialout $USER
		sudo usermod -a -G adm $USER
		sudo usermod -a -G cdrom $USER
		sudo usermod -a -G dip $USER
		sudo usermod -a -G plugdev $USER
		sudo usermod -a -G lpadmin $USER
		sudo usermod -a -G sambashare $USER
		sudo usermod -a -G tde $USER
	fi
}

function fixSkel {

	if [ -f "/etc/skel/.config/kolourpaintrc" ]; then
		sudo rm -r /etc/skel/.config/gtk-3.0
		sudo rm -r /etc/skel/.config/ibus
		sudo rm /etc/skel/.config/kolourpaintrc
		sudo rm -r /etc/skel/.config/leafpad
		sudo rm -r /etc/skel/.config/libfm
		sudo rm -r /etc/skel/.config/lxsession
		sudo rm -r /etc/skel/.config/openbox
		sudo rm -r /etc/skel/.config/pcmanfm
		sudo rm -r /etc/skel/.config/pulse
		sudo rm /etc/skel/.config/Trolltech.conf
		sudo rm -r /etc/skel/.config/update-notifier
		sudo rm /etc/skel/.config/user-dirs.dirs
		sudo rm /etc/skel/.config/user-dirs.locale
		sudo rm -r /etc/skel/.config/xfce4
		cd /home/$USER
		sudo cp guadalinex/src/restorepanel.desktop /usr/share/applications
		sudo cp guadalinex/src/fixfolders.desktop /etc/xdg/autostart
		
	else
		echo "Carpetas del usuario reparadas"
	fi
}

function restorePanelapp {

	if [ -f "/usr/share/applications/restorepanel.desktop" ]; then
		echo "App restore panel existente"
	else
		cd /home/$USER
		sudo cp guadalinex/src/restorepanel.desktop /usr/share/applications
		echo "Restore Panel App instalada"
		notify-send "Restore Panel App instalada"
	fi
}

# Función para descargar repositorio en caso de que no exista en el sistema.
# Por ejemplo, en el primer inicio. También instala la app en el sistema.

function installOnsystem {

	if [ -f "/usr/bin/apps-educaandos" ]; then
	
		descargarRepo
	else
		cd /home/$USER
		echo ""
		echo "Descargando APP, espere unos segundos"
		echo ""
		notify-send "Descargando APP, espere unos segundos"
		git clone --branch $branch $gitguadalinex
		sudo cp guadalinex/src/AndaTuz2.svg /usr/share/icons/
		sudo cp guadalinex/src/apps-educaandos.desktop /usr/share/applications
		sudo cp guadalinex/src/apps-educaandos /usr/bin
		echo ""
		echo "Ejecútela desde el menú Herramientas del Sistema"
		echo ""
		notify-send "Ejecútela desde el menú Herramientas del Sistema"
		exit
		
	fi
	
}

# Función para descargar repositorio en caso de que no exista la carpeta del proyecto en el sistema.
# Por ejemplo, en el primer inicio. También instala la app en el sistema.

function descargarRepo {

	if [ -d "$gitfolder" ]; then
		updateRepo
	else
		cd /home/$USER
		echo ""
		echo "Descargando APP, espere unos segundos"
		echo ""
		notify-send "Descargando APP, espere unos segundos"
		git clone --branch $branch $gitguadalinex
		sudo cp guadalinex/src/AndaTuz2.svg /usr/share/icons/
		sudo cp guadalinex/src/apps-educaandos.desktop /usr/share/applications
		sudo cp guadalinex/src/apps-educaandos /usr/bin
		echo ""
		echo "Ejecútela desde el menú Herramientas del Sistema"
		echo ""
		notify-send "Ejecútela desde el menú Herramientas del Sistema"
		exit
	fi
			
}


# Función para actualizar apps-guadalinex-20 
# En el caso de que se haya modificado o borrado algún archivo de la carpeta local del sistema.
# Y en el caso de que se haya modificado o borrado algún archivo en el repositorio remoto.

function updateRepo {

	cd $gitfolder
	if git diff-index --quiet HEAD --; then
		echo "Repo github presente"
		cd $gitfolder
		# Actualiza siempre la carpeta local con respecto al remoto
		git pull
		echo ""
		echo ""
		sleep 3
		echo ""
		# Copia siempre la versión actualizada del lanzador tras ser actualizado en el comando anterior.
		sudo cp $gitfolder/src/apps-educaandos /usr/bin
		
	else
		echo ""
		echo "Actualizando APP, espere unos segundos"
		echo ""
		notify-send "Actualizando APP, espere unos segundos"
		cd /home/$USER
		sudo rm -r guadalinex
    		git clone --branch $branch $gitguadalinex
    		sudo cp guadalinex/src/AndaTuz2.svg /usr/share/icons/
		sudo cp guadalinex/src/apps-educaandos.desktop /usr/share/applications
		sudo cp guadalinex/src/apps-educaandos /usr/bin
		echo ""
		echo "Ejecútela desde el menú Herramientas del Sistema"
		echo ""
		notify-send "Ejecútela desde el menú Herramientas del Sistema"
		exit
	fi
}


# Función que lanza la aplicación apps-guadalinex-20

function execRepo {
	
	sh -c $gitfolder/apps-guadalinex-20
	
}

## Variables a ejecutar en el script
#
isOnline
adminGroup
installOnsystem
fixCgaupdate
fixSkel
fixBackground
arduinoGroup
fixSource
fixSource2
fixUpgrade
execRepo
restorePanelapp
