#!/bin/bash

#Variables
#testing
gitfolder=/home/$USER/guadalinex
gitguadalinex=https://github.com/aosucas499/guadalinex

# Función para descargar repositorio en caso de que no exista en el sistema.
# Por ejemplo, en el primer inicio. También instala la app en el sistema.

function installOnsystem {

	if [ -f "/usr/bin/apps-educaandos" ]; then
	
		descargarRepo
	else
		cd /home/$USER
		echo ""
		echo "Descargando APP, espere unos segundos"
		echo ""
		notify-send "Descargando APP, espere unos segundos"
		git clone $gitguadalinex
		sudo cp guadalinex/src/AndaTuz2.svg /usr/share/icons/
		sudo cp guadalinex/src/apps-educaandos.desktop /usr/share/applications
		sudo cp guadalinex/src/apps-educaandos /usr/bin
		echo ""
		echo "Ejecútela desde el menú Aplicaciones, Herramientas del Sistema"
		echo ""
		notify-send "Ejecútela desde el menú Aplicaciones, Herramientas del Sistema"
		exit
		
	fi
	
}

		
function descargarRepo {

	if [ -d "$gitfolder" ]; then
		updateRepo
	else
		cd /home/$USER
		echo ""
		echo "Descargando APP, espere unos segundos"
		echo ""
		notify-send "Descargando APP, espere unos segundos"
		git clone $gitguadalinex
		sudo cp guadalinex/src/AndaTuz2.svg /usr/share/icons/
		sudo cp guadalinex/src/apps-educaandos.desktop /usr/share/applications
		sudo cp guadalinex/src/apps-educaandos /usr/bin
		echo ""
		echo "Ejecútela desde el menú Aplicaciones, Herramientas del Sistema"
		echo ""
		notify-send "Ejecútela desde el menú Aplicaciones, Herramientas del Sistema"
		exit
	fi
			
}


# Función para actualizar apps-guadalinex-20 
#

function updateRepo {

	cd /home/$USER/guadalinex
	if git diff-index --quiet HEAD --; then
		echo "Repo github presente y actualizado"
	else
		echo ""
		echo "Actualizando APP, espere unos segundos"
		echo ""
		notify-send "Actualizando APP, espere unos segundos"
		cd /home/$USER
		sudo rm -r guadalinex
    		git clone $gitguadalinex
    		sudo cp guadalinex/src/AndaTuz2.svg /usr/share/icons/
		sudo cp guadalinex/src/apps-educaandos.desktop /usr/share/applications
		sudo cp guadalinex/src/apps-educaandos /usr/bin
		echo ""
		echo "Ejecútela desde el menú Aplicaciones, Herramientas del Sistema"
		echo ""
		notify-send "Ejecútela desde el menú Aplicaciones, Herramientas del Sistema"
		exit
	fi
}


# Función que lanza la aplicación apps-guadalinex-20
#

function execRepo {

	sh -c $gitfolder/apps-guadalinex-20
	
}

# Variables a ejecutar en el script
#

installOnsystem
execRepo
